name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemShtepenko/kivy-buildozer-action@v1.2
        id: buildozer
        with:
          save_artifact: true

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BeastAITrader-APK
          path: bin/*.apk
