name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build APK with Buildozer
        uses: ArtemShtepenko/kivy-buildozer-action@v1.2
        with:
          save_artifact: true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: My-Bybit-Bot
          path: bin/*.apk
